// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbftmgzsdobxftetokbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZnRtZ3pzZG9ieGZ0ZXRva2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTU2OTQsImV4cCI6MjA2NjM3MTY5NH0.1CMM018AVEpzN7DKV25shtKgTD4EYUhayiZwt0OocSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);